//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.09 at 03:46:04 PM IST 
//


package com.soap.service.calculation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="input1" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="input2" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "input1",
    "input2"
})
@XmlRootElement(name = "CalculationRequest")
public class CalculationRequest {

    protected int input1;
    protected int input2;

    /**
     * Gets the value of the input1 property.
     * 
     */
    public int getInput1() {
        return input1;
    }

    /**
     * Sets the value of the input1 property.
     * 
     */
    public void setInput1(int value) {
        this.input1 = value;
    }

    /**
     * Gets the value of the input2 property.
     * 
     */
    public int getInput2() {
        return input2;
    }

    /**
     * Sets the value of the input2 property.
     * 
     */
    public void setInput2(int value) {
        this.input2 = value;
    }

}
